games_killer_index:
    path:     /
    defaults: { _controller: GamesKillerBundle:Default:index }

games_killer_createKiller:
    path:     /newKiller
    defaults: { _controller: GamesKillerBundle:Default:createKiller }
    
games_killer_consultKiller:
    path:     /myKillers/{name}
    defaults: { _controller: GamesKillerBundle:Default:consultKiller }
    
games_killer_consultListKillers:
    path:     /myKillers
    defaults: { _controller: GamesKillerBundle:Default:consultListKillers }
    
games_killer_setKillerOn:
    path:     /setKillerOn/{id}
    defaults: { _controller: GamesKillerBundle:Default:setKillerOn }