games_killer_index:
    path:     /
    defaults: { _controller: GamesKillerBundle:Default:index }
    
games_killer_presentation:
    path:     /presentation
    defaults: { _controller: GamesKillerBundle:Default:presentation }

games_killer_createKiller:
    path:     /newKiller
    defaults: { _controller: GamesKillerBundle:Default:createKiller }
    
games_killer_consultKiller:
    path:     /myKillers/{name}
    defaults: { _controller: GamesKillerBundle:Default:consultKiller }
    
games_killer_consultCreatedListKillers:
    path:     /myCreations
    defaults: { _controller: GamesKillerBundle:Default:consultCreatedListKillers }
    
games_killer_consultParticipationListKillers:
    path:     /myParticipations
    defaults: { _controller: GamesKillerBundle:Default:consultParticipationListKillers }
    
games_killer_setKillerOn:
    path:     /setKillerOn/{id}
    defaults: { _controller: GamesKillerBundle:Default:setKillerOn }

games_killer_ajaxrqValidatePlayer:
    pattern:  /ajaxrqValidatePlayer
    defaults: { _controller: GamesKillerBundle:Default:ajaxrqValidatePlayer}
    
games_killer_ajaxrqGetAdresseComplete:
    pattern:  /ajaxrqGetAdresseComplete
    defaults: { _controller: GamesKillerBundle:Default:ajaxrqGetAdresseComplete}
