games_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: GamesUserBundle:Default:index }

games_user_create:
    path:     /create
    defaults: { _controller: GamesUserBundle:Default:create }
    