<?php

namespace Games\KillerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KillerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KillerRepository extends EntityRepository
{
    
    public function findMyParticpationListKillers($userId)
    {
        $qb = $this->createQueryBuilder('k');
    
        $qb->join('k.players', 'players')
        ->addSelect('players');
    
        $qb->where('players.user = :userid')
        ->setParameter('userid', $userId);
    
        return $qb
        ->getQuery()
        ->getResult()
        ;
    }
}
