<?php

namespace Games\KillerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KillerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KillerRepository extends EntityRepository
{
	
}
