<?php

namespace Games\KillerBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Games\KillerBundle\Entity\Killer;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function findAllowedPlayers(Killer $killer)
    {
          $qb = $this->createQueryBuilder('p');
          
          $qb->where('p.isAllowed = true')
             ->andWhere('p.killer = :id')
             ->setParameter('id', $killer->getId())
          ;
          
          return $qb
            ->getQuery()
            ->getResult()
          ;
    }
}
